project:
  type: website


# filters:
#   - day_01_nvcc/src/hello.cu
# format:
#   html:
#     code-tools: true
#     code-fold: false
#     code-block-background: true
#     code-block-border-left: "#31BAE9"
#     highlight-style: github


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    page-layout: full

website:
  twitter-card:
      creator: "@xl0xl0xl0"
  open-graph: true
  # repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "http://github.com/xl0/cuda-100"
      - icon: twitter
        href: "https://x.com/xl0xl0xl0"
  sidebar:
    style: floating
    # contents:
    # - index.ipynb
    # - section: "Source Files"
    #   contents:
    #     - text: "hello"
    #       file: day_01_nvcc/src/hello.cu
    #       format: c++


metadata-files: [nbdev.yml, sidebar.yml]